// JsFromRoutes CacheKey f3dc8ea3f13f1168670732a1d1eed3db
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: /* #__PURE__ */ definePathHelper('get', '/api/users/password/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/api/users/password/edit'),
  update: /* #__PURE__ */ definePathHelper('patch', '/api/users/password'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/users/password'),
}
