// JsFromRoutes CacheKey 03a538efa0ed5bb7693656f0a3ae1be0
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: /* #__PURE__ */ definePathHelper('get', '/api/users/sign_in'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/users/sign_in'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/api/users/sign_out'),
}
