// JsFromRoutes CacheKey e9bec765d1b3f0b7970e0f0f16ac5baa
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  current: /* #__PURE__ */ definePathHelper('get', '/api/users/current'),
  index: /* #__PURE__ */ definePathHelper('get', '/api/users'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/users'),
  new: /* #__PURE__ */ definePathHelper('get', '/api/users/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/api/users/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/api/users/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/api/users/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/api/users/:id'),
}
